- hosts: R1
  gather_facts: false
  connection: local
  tasks:
    - include_vars: variables.yml
    - include: R1.yml

- hosts: R2
  gather_facts: false
  connection: local
  tasks:
    - include_vars: variables.yml
    - include: R2.yml

  