---
- hosts: R1
  gather_facts: false
  connection: local

  vars_prompt:
    - name: tunnelIP
      prompt: "[R1] What is the tunnel ip"
      private: no
    - name: tunnelSource
      prompt: "[R1] What is the tunnel source"
      private: no
    - name: tunnelDestination
      prompt: "[R1] What is the tunnel destination"
      private: no

  tasks:
    - name: Change Host name
      ios_config:
        lines:
          - "ip address {{ tunnelIP }} 255.255.255.252"
          - "tunnel source {{ tunnelSource }}"
          - "tunnel destination {{ tunnelDestination }}"
        parents: int tunnel 0
