- name: multiple commands
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: run multiple
      ios_command:
          commands:
              - show protocols
              - show ip int brief

      register: print_output

    - debug: var=print_output.stdout_lines