---
- name: Change Banner
  ios_banner:
    banner: motd
    text: "{{ R1_banner }}"
    state: present

- name: Add default-router interface
  ios_config:
    parents: "int {{ DHCP_Default_Router_Interface_R1 }}"
    lines:
      - "ip addr {{ DHCP_Default_Router_R1 }} {{ DHCP_Default_Router_Subnet_R1 }}"

- name: Add DHCP config
  ios_config:
    parents: ip dhcp pool {{ DHCP_Pool_R1 }}
    lines:
      - "network {{ item.value.ip }} {{ item.value.subnet }}"
      - "default-router {{ DHCP_Default_Router_R1 }}"
  loop: "{{ q('dict', DHCPNetwork_R1) }}"

- name: Clear OSPf config
  ios_config:
    lines:
      - "no router ospf 1"

- name: add OSPF
  ios_config:
    parents: router ospf 1
    lines:
      - "network {{ item.value.ip }} {{ item.value.wildcardMask }} area {{ item.value.area }}"
  loop: "{{ q('dict', OSPFNetwork_R1) }}"

- name: Create VPN tunnel
  ios_config:
    lines:
      - "ip address {{ R1tunnelIP }} 255.255.255.252"
      - "tunnel source {{ tunnelSource }}"
      - "tunnel destination {{ tunnelDestination }}"
    parents: int tunnel 0
