---
- name: Change Banner
  ios_banner:
    banner: motd
    text: "{{ R2_banner }}"
    state: present

- name: Add default-router interface
  ios_config:
    parents: "int {{ DHCP_Default_Router_Interface_R2 }}"
    lines:
      - "ip addr {{ DHCP_Default_Router_R2 }} {{ DHCP_Default_Router_Subnet_R2 }}"

- name: Add DHCP config
  ios_config:
    parents: ip dhcp pool {{ DHCP_Pool_R2 }}
    lines:
      - "network {{ item.value.ip }} {{ item.value.subnet }}"
      - "default-router {{ DHCP_Default_Router_R2 }}"
  loop: "{{ q('dict', DHCPNetwork_R2) }}"

- name: Clear OSPf config
  ios_config:
    lines:
      - "no router ospf 1"

- name: add OSPF
  ios_config:
    parents: router ospf 1
    lines:
      - "network {{ item.value.ip }} {{ item.value.wildcardMask }} area {{ item.value.area }}"
  loop: "{{ q('dict', OSPFNetwork_R2) }}"

- name: Create VPN tunnel
  ios_config:
    lines:
      - "ip address {{ R2tunnelIP }} 255.255.255.252"
      - "tunnel source {{ tunnelDestination }}"
      - "tunnel destination {{ tunnelSource }}"
    parents: int tunnel 0
